version: 0.0
os: linux
files:
  - source: ./scripts
    destination: /home/ec2-user/myapp
permissions: 
  - object: /home/ec2-user/myapp
    owner: root
    mode: 777
hooks:
  AfterInstall: 
    - location: scripts/after-install.sh
      runas: root
       
  ApplicationStart:
    - location: scripts/runapp.sh
      runas: root